# Generated by Django 4.2.7 on 2023-11-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(to='identification.user'),
        ),
    ]
