# Generated by Django 4.2.7 on 2023-11-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('ingredients', models.JSONField(default=[])),
                ('instructions', models.JSONField(default=[])),
                ('preperation_time', models.IntegerField(default=0)),
                ('cooking_time', models.IntegerField(default=0)),
                ('servings', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('category', models.TextField(default='other')),
                ('notes', models.TextField(default='')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.user')),
                ('comments', models.ManyToManyField(blank=True, null=True, to='recipe.comment')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.image')),
            ],
        ),
    ]
