# Generated by Django 4.2.7 on 2023-11-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(blank=True, to='recipe.comment'),
        ),
    ]
