# Generated by Django 4.2.7 on 2023-11-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(to='recipe.comment'),
        ),
    ]
