# Generated by Django 4.2.7 on 2023-11-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_delete_image_comment_created_recipe_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reviewers',
            field=models.IntegerField(default=0),
        ),
    ]
